$ErrorActionPreference = "Stop"

$projectDir = Split-Path -Parent $PSScriptRoot
$enhancementPath = Join-Path $projectDir "dashboard.js"
$bundlePath = Join-Path $projectDir "dashboard-bundle.js"
$webServerUrl = "https://oi.esphome.io/v3/www.js"

$webServerSource = (Invoke-WebRequest -UseBasicParsing $webServerUrl).Content
$enhancementSource = Get-Content -Raw -Encoding UTF8 -LiteralPath $enhancementPath
$header = "// Generated by scripts/build-dashboard-bundle.ps1.`n// ESPHome web UI: $webServerUrl`n"

[System.IO.File]::WriteAllText(
  $bundlePath,
  $header + $webServerSource + "`n" + $enhancementSource,
  [System.Text.UTF8Encoding]::new($false)
)

Write-Host "Built $bundlePath"
