$ErrorActionPreference = "Stop"

$projectDir = Split-Path -Parent $PSScriptRoot
$enhancementPath = Join-Path $projectDir "dashboard.js"
$bundlePath = Join-Path $projectDir "dashboard-bundle.js"
$webServerUrl = "https://oi.esphome.io/v3/www.js"

$webServerSource = (Invoke-WebRequest -UseBasicParsing $webServerUrl).Content
$enhancementSource = Get-Content -Raw -Encoding UTF8 -LiteralPath $enhancementPath
$header = @"
// Generated by scripts/build-dashboard-bundle.ps1.
// ESPHome web UI: $webServerUrl
// If custom enhancement fails after this bundle arrives, reveal ESPHome's
// stock UI instead of leaving the recovery page hidden indefinitely.
setTimeout(() => document.querySelector('link[href="/0.css"]')?.remove(), 12000);
"@

[System.IO.File]::WriteAllText(
  $bundlePath,
  $header + "`n" + $webServerSource + "`n" + $enhancementSource,
  [System.Text.UTF8Encoding]::new($false)
)

Write-Host "Built $bundlePath"
