[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"
$projectRoot = Split-Path -Parent $PSScriptRoot
$sourcePath = Join-Path $projectRoot "web/index.html"
$headerPath = Join-Path $projectRoot "include/dashboard_gz.h"

$htmlBytes = [System.IO.File]::ReadAllBytes($sourcePath)
$memory = [System.IO.MemoryStream]::new()
$gzip = [System.IO.Compression.GZipStream]::new(
    $memory,
    [System.IO.Compression.CompressionLevel]::SmallestSize,
    $true
)
$gzip.Write($htmlBytes, 0, $htmlBytes.Length)
$gzip.Dispose()
$compressed = $memory.ToArray()
$memory.Dispose()

$rows = [System.Collections.Generic.List[string]]::new()
for ($offset = 0; $offset -lt $compressed.Length; $offset += 16) {
    $last = [Math]::Min($offset + 15, $compressed.Length - 1)
    $values = for ($index = $offset; $index -le $last; $index++) {
        "0x{0:X2}" -f $compressed[$index]
    }
    $suffix = if ($last -lt $compressed.Length - 1) { "," } else { "" }
    $rows.Add("  " + ($values -join ", ") + $suffix)
}

$header = @"
#pragma once
#include <Arduino.h>

// Generated by scripts/build-dashboard.ps1 from web/index.html.
const uint8_t dashboard_html_gz[] PROGMEM = {
$($rows -join "`n")
};
constexpr size_t dashboard_html_gz_len = sizeof(dashboard_html_gz);
"@

[System.IO.File]::WriteAllText(
    $headerPath,
    $header + "`n",
    [System.Text.UTF8Encoding]::new($false)
)

[pscustomobject]@{
    Source = $sourcePath
    Header = $headerPath
    HtmlBytes = $htmlBytes.Length
    GzipBytes = $compressed.Length
}
